platform :ios, '8.0'

target 'GeneralLock' do
  
  pod 'AFNetworking'
  pod 'Masonry'
  pod 'ReactiveObjC'
  pod 'IQKeyboardManager'
  pod 'MJExtension'
  pod 'YYWebImage'
  pod 'MBProgressHUD'
  pod 'JPush'
  pod 'JXTAlertManager'
  pod 'YBDictionaryToModel'
  pod 'MJRefresh'
  pod 'AMap3DMap'
  pod 'AMapLocation'
  pod 'Toast'
  pod "XJYChart"

end
